version: '3'
services:
  flask:
    build: .
    command: gunicorn -b 0.0.0.0:5555 main:app --reload --timeout 5
    environment: 
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - PYTHONBUFFERED=True
    ports: 
      - "5555:5555"
    volumes: 
      - ./:/app